# Site settings
title: VIAR
description: A simple site powered by GitHub Pages and Jekyll
author: Your Name
url: https://yourusername.github.io # Replace with your GitHub Pages URL
baseurl: "" # Keep it blank unless the site is in a subdirectory

# Theme settings
theme: minimal # Replace with your chosen GitHub Pages theme

# Plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
