theme: jekyll-theme-modernist
# Easy to integrate supported themes: 
# https://pages.github.com/themes/

show_downloads: true

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: VIAR
description: Project for UCLA ECEM202A/CSM213A (Fall 2024)
